import Head from "next/head";
import Link from "next/link";
import Button from "@/components/Button";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button btnClass={"btn-primary"} btnName={"Sign Up!"}/>
    </>
  );
}
